### ISSUE TITLE
Problem with "Downloading data" in tutorial 5

### ISSUE THREAD

**Issue by eliadl** [rragundez/data-science-summit-2016#1]
When attempting to download the data via this code:
```
data_filename = download('notMNIST_small.tar.gz')
print '\nData folders:'
data_folders = untar(data_filename)
```
This is the output I get:

> ('Dowloading ', 'notMNIST_small.tar.gz', 'into ', 'data/notMNIST_small.tar.gz')
> ---------------------------------------------------------------------------
> IOError                                   Traceback (most recent call last)
> <ipython-input-6-ca8312ba486a> in <module>()
> ----> 1 data_filename = download('notMNIST_small.tar.gz')
>       2 print '\nData folders:'
>       3 data_folders = untar(data_filename)
> 
> <ipython-input-3-c8f57270de33> in download(filename)
>      19     if not os.path.exists(destination_file):
>      20         print("Dowloading ", filename, "into ", destination_file)
> ---> 21         urlretrieve(url + filename, destination_file)
>      22     else:
>      23         print "File already exists: %s" %filename
> 
> /usr/lib/python2.7/urllib.pyc in urlretrieve(url, filename, reporthook, data, context)
>      96     else:
>      97         opener = _urlopener
> ---> 98     return opener.retrieve(url, filename, reporthook, data)
>      99 def urlcleanup():
>     100     if _urlopener:
> 
> /usr/lib/python2.7/urllib.pyc in retrieve(self, url, filename, reporthook, data)
>     247             headers = fp.info()
>     248             if filename:
> --> 249                 tfp = open(filename, 'wb')
>     250             else:
>     251                 import tempfile
> 
> IOError: [Errno 2] No such file or directory: 'data/notMNIST_small.tar.gz'

This persists even if I create the folder "data" and download there the file.
Am I missing something?

**Comment by ragundez** [comment]
​You have to create the folder data prior to the command, this happens
because github doesn't allow to commit empty folders. I should have made
the code such that it creates the folder prior ti that command sorry.
I think if you want to created via python you need these lines prior to the
download function:
if not os.path.exists('data'):
    os.makedirs('data')

I hope that works,
regards

On 5 June 2016 at 23:13, Eliad Levy <notifications@github.com> wrote:

> When attempting to download the data via this code:
>
> data_filename = download('notMNIST_small.tar.gz')
> print '\nData folders:'
> data_folders = untar(data_filename)
>
> This is the output I get:
>
> ('Dowloading ', 'notMNIST_small.tar.gz', 'into ',
> 'data/notMNIST_small.tar.gz')
>
> IOError Traceback (most recent call last)
> in ()
> ----> 1 data_filename = download('notMNIST_small.tar.gz')
> 2 print '\nData folders:'
> 3 data_folders = untar(data_filename)
>
> in download(filename)
> 19 if not os.path.exists(destination_file):
> 20 print("Dowloading ", filename, "into ", destination_file)
> ---> 21 urlretrieve(url + filename, destination_file)
> 22 else:
> 23 print "File already exists: %s" %filename
>
> /usr/lib/python2.7/urllib.pyc in urlretrieve(url, filename, reporthook,
> data, context)
> 96 else:
> 97 opener = _urlopener
> ---> 98 return opener.retrieve(url, filename, reporthook, data)
> 99 def urlcleanup():
> 100 if _urlopener:
>
> /usr/lib/python2.7/urllib.pyc in retrieve(self, url, filename, reporthook,
> data)
> 247 headers = fp.info()
> 248 if filename:
> --> 249 tfp = open(filename, 'wb')
> 250 else:
> 251 import tempfile
>
> IOError: [Errno 2] No such file or directory: 'data/notMNIST_small.tar.gz'
> This persists even if I create the folder "data" and download there the
> file.
> Am I missing something?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ragundez/data-science-summit-2016/issues/1>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AP32dF2a-mLLiDODHiEYcJiS1wj3moGTks5qIy3dgaJpZM4Iub0T>
> .
>



-- 
​


*​​Dr. ir. *

*Rodrigo Agundez*
Data Scientist
De Bruyn Kopsstraat 9
m +31 (0)6 48 58 40 17
2288 EC Rijswijk (ZH)
t +31 (0)70 319 50 00
The Netherlands
e ragundez@qualogy.com
Qualogy.com
<http://www.qualogy.com/>

-- 
DISCLAIMER:

*The information contained in this message may be confidential or 
privileged and is only intended for the use of the addressee. If you are 
not the intended recipient, you are requested by Qualogy to report this to 
the sender and to delete the message and you are notified that the use or 
distribution of the information contained in this message is strictly 
prohibited and unlawful.*

**Comment by ragundez** [comment]
​You have to create the folder data prior to the command, this happens because github doesn't allow to commit empty folders. I should have made the code such that it creates the folder prior to that command sorry. 
If you want to create the folder via python you need these lines prior to the download function:
``` python
if not os.path.exists('data'):
    os.makedirs('data')
```

**Comment by rragundez** [comment]
I just committed the updated notebook, take a look.
